### ISSUE TITLE
initialize_logging should be idempotent

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos-log-cpp#8]
Some fixtures in the `koinos_chain` unit tests call `initialize_logging()` multiple times, leading the same log message to be displayed multiple times.

There are two different possible approaches to a fix:

- (1) Call `remove_all_sinks()` to attempt to reset Boost logging to a pristine state
- (2) Change `initialize_logging()` to be a no-op except for the first time it is called

The first is more "correct."  However it may be hard; quickly skimming docs and code for Boost logging, it may not have methods to fully reset all of the configuration that is done by `initialize_logging()`.

I personally lean toward (2).  Perhaps we should add an error message, or even `exit(1)`, when logging is initialized multiple times, and then fix the tests to not initialize logging multiple times.

**Comment by sgerbino** [comment]
We should do (1) and it has been resolved in `koinos-chain`.
